camera_driver_3d:
  ros__parameters:
    cfg: config/cameratcp_sim.yaml
    publish_tf: true
    camera.x: -0.0240785
    camera.y: 0.183801
    camera.z: 0.495747
    camera.rx: -3.00009
    camera.ry: 0.0952431
    camera.rz: 2.80206
    tool.x: 0.0
    tool.y: 0.0
    tool.z: 0.0
    tool.rx: 0.0
    tool.ry: 0.0
    tool.rz: 0.0
    y_min: -0.015
    y_max: 0.015
    z_min: -0.035
    z_max: 0.015
    y_min_f: -0.002
    y_max_f: 0.007
    percentile_low: 0.333
    percentile_high: 0.666
    number_points_threshold: 25
    no_detection_count_threshold: 3
camera_node:
  ros__parameters:
    trigger_mode: 2
    strobe_polarity: 0
    saturation: 64
    gamma: 106
    exposure_time: 4.3
    analog_gain: 64
    frame_rate: 30.0
robot_driver_fanuc:
  ros__parameters:
    so_file_path: sim/lib/libFanucRobot.so
    robot_ip: 127.0.0.1
    robot_port: 60008
    target_register_index: 100
    target_register_value: 100
    weld_id: 101
    weld_type: 1
    weld_layer: 1
    publish_rate: 20.0
    motion_period: 18.0
    publish_tool_pose: false
    publish_robot_info: false
    alarm_enabled: false
    emg_enabled: false
data_collect_node:
  ros__parameters:
    save_dir_root: data/sim
    image_save_interval: 2
    image_log_save_interval: 3
    height_log_save_interval: 4
    fix_scan_interval: 6
    auto_save_flag: 0
    target_register_index: 100
    weld_type_mapping:
      1: "对接焊缝"
      2: "角接焊缝"
      3: "搭接焊缝"
