- ros_topic_name: "/image_topic"
  gz_topic_name: "/panda_weld_arm/pool_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/tcp_cloud_raw"
  gz_topic_name: "/panda_weld_arm/tcp_rgbd/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

