camera_driver_3d:
  ros__parameters:
    cfg: /home/kyle/sany/weld_data_collect_ws/src/camera_3d_driver/config/cameratcp.yaml
    publish_tf: true
camera_node:
  ros__parameters:
    trigger_mode: 2
    strobe_polarity: 0
    saturation: 57
    gamma: 106
    exposure_time: 4.2
    analog_gain: 58
    frame_rate: 60.90000000000001
robot_driver_fanuc:
  ros__parameters:
    so_file_path: /home/kyle/sany/weld_data_collect_ws/src/fanuc_robot/lib/libFanucRobot.so
    robot_ip: 10.16.140.114
    robot_port: 60013
    target_register_index: 100
data_collect_node:
  ros__parameters:
    save_dir_root: /home/kyle/sany/weld_data_collect_ws/data
    image_save_interval: 2
    image_log_save_interval: 3
    height_log_save_interval: 4
    fix_scan_interval: 6
    auto_save_flag: 0
    target_register_index: 100
